//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLogOcasa.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTV_Moni_Error
    {
        public string Clave { get; set; }
        public Nullable<System.DateTime> Fecha_sys { get; set; }
        public Nullable<System.DateTime> Fecha_Vcia { get; set; }
        public string Usuario { get; set; }
        public string Desc_Corta { get; set; }
        public string Desc_Larga { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> IdDocumento { get; set; }
        public string FechaError { get; set; }
        public string NombreArchivo { get; set; }
        public Nullable<decimal> IdIntegracion { get; set; }
        public string IdPais { get; set; }
        public Nullable<decimal> IdEstado { get; set; }
        public Nullable<decimal> IdResponsable { get; set; }
        public string FechaCierre { get; set; }
        public string Error { get; set; }
        public string Observacion { get; set; }
    
        public virtual DTV_Moni_Estado DTV_Moni_Estado { get; set; }
        public virtual DTV_Moni_Integ DTV_Moni_Integ { get; set; }
        public virtual DTV_Moni_Respon DTV_Moni_Respon { get; set; }
    }
}
